# Generated by Django 4.2.14 on 2024-08-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_cooking_time_recipe_cookingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(help_text='Enter the ingredients, separated by a comma', max_length=225),
        ),
    ]
